"""Cell definitions for the dual-scenario AFMLF unseen-container case study notebook."""

from __future__ import annotations


def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": [text]}


def code(text: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [text],
    }


def build_case_study_notebook() -> list[dict]:
    return [
        md(
            "# AFMLF Unseen Container Case Study\n\n"
            "**Deployment demonstration — not a new research experiment.**\n\n"
            "This notebook teaches AFMLF as **two distinct levels**:\n\n"
            "| Level | What it covers |\n"
            "|-------|----------------|\n"
            "| **Individual container monitoring** | Forecast → rolling errors → drift → diagnostics |\n"
            "| **Global model lifecycle** | Cohort aggregation → trigger policy → offline retrain → deployment recommendation |\n\n"
            "The deployed Hybrid model is a **global model** trained across many containers. "
            "A single drifting unseen container does **not** retrain it — only cohort-level evidence can.\n\n"
            "> **Incumbent:** `hybrid_v1` from official experiment (read-only)\n\n"
            "**Kernel required:** `tf_metal_env`. One-time setup:\n"
            "```bash\n"
            "tf_metal_env/bin/python -m ipykernel install --user --name=tf_metal_env --display-name='tf_metal_env'\n"
            "```"
        ),
        md(
            "## 1. Introduction\n\n"
            "The official AFMLF evaluation proved lifecycle governance at thesis scale (99 containers). "
            "This notebook complements it in two parts:\n\n"
            "1. **Section 2** — Individual container monitoring on two unseen workloads (stable vs drifting)\n"
            "2. **Section 3** — Cohort-level lifecycle using the **official 99-container experiment**\n"
            "3. **Section 4** — How the two levels differ, with an architecture diagram\n\n"
            "No AFMLF methodology is changed. All figures are generated live from data."
        ),
        code(
            "import json\nimport sys\nfrom pathlib import Path\n\n"
            "import matplotlib.patches as mpatches\n"
            "import matplotlib.pyplot as plt\nimport numpy as np\nimport pandas as pd\n\n"
            "try:\n"
            "    from IPython.display import display, Markdown\n"
            "except ImportError:\n"
            "    display = print\n"
            "    Markdown = print\n\n"
            "REPO = Path('..').resolve()\n"
            "sys.path.insert(0, str(REPO))\n\n"
            "from utils.adaptive_lifecycle import plots as afmlf_plots\n"
            "from utils.adaptive_lifecycle.config import AFMLFConfig, DeploymentRecommendation\n"
            "from utils.adaptive_lifecycle.candidate_retraining import load_model_bundle\n"
            "from utils.adaptive_lifecycle.diagnostics import DiagnosticClass, classify_container\n"
            "from utils.adaptive_lifecycle.drift_detection import detect_container_drift, drift_threshold\n"
            "from utils.adaptive_lifecycle.monitoring import (\n"
            "    build_container_series,\n"
            "    forecast_at_origin,\n"
            "    generate_origin_indices,\n"
            ")\n"
            "from utils.adaptive_lifecycle.rolling_metrics import append_rolling_metrics\n\n"
            "OFFICIAL_EXP = [p for p in sorted(REPO.glob('experiments/adaptive_forecast_model_lifecycle_*')) if (p / 'OFFICIAL_RUN').exists()][-1]\n"
            "CASE_OUT = REPO / 'notebooks' / 'outputs' / 'afmlf_case_study'\n"
            "CASE_OUT.mkdir(parents=True, exist_ok=True)\n"
            "SCAN_CSV = CASE_OUT / 'unseen_scan.csv'\n\n"
            "CFG = AFMLFConfig.from_json(OFFICIAL_EXP / 'config' / 'afmlf_config.json')\n"
            "COHORT = set(pd.read_csv(REPO / CFG.baseline_evaluation_csv)['container_id'])\n"
            "train_df = pd.read_parquet(REPO / CFG.train_df_path)\n"
            "val_df = pd.read_parquet(REPO / CFG.val_df_path)\n\n"
            "with (REPO / 'production/hybrid/metadata/unseen_container_ids.json').open() as fh:\n"
            "    UNSEEN_IDS = json.load(fh)['container_ids']\n"
            "UNSEEN_IDS = [c for c in UNSEEN_IDS if c not in COHORT]\n"
            "available = [c for c in UNSEEN_IDS if c in set(train_df['container_id']) | set(val_df['container_id'])]\n\n"
            "INCUMBENT_DIR = OFFICIAL_EXP / 'versions' / 'hybrid_v1'\n"
            "incumbent, res_mean, res_std = load_model_bundle(INCUMBENT_DIR)\n"
            "RESCAN_CONTAINERS = False  # set True to rerun full unseen scan (~1 min)\n\n"
            "print('Python:', sys.executable)\n"
            "print('Official experiment:', OFFICIAL_EXP.name)\n"
            "print('Unseen containers in dataset:', len(available))"
        ),
        code(
            "def forecast_detail(series, origin, model, res_mean, res_std, config):\n"
            "    from sklearn.preprocessing import MinMaxScaler\n"
            "    from prophet import Prophet\n"
            "    history = series.iloc[:origin].copy()\n"
            "    future = series.iloc[origin:origin + config.forecast_horizon].copy()\n"
            "    scaler = MinMaxScaler(feature_range=(0, 1))\n"
            "    history['cpu_scaled'] = scaler.fit_transform(history[['cpu']])\n"
            "    future['cpu_scaled'] = scaler.transform(future[['cpu']])\n"
            "    prophet_train = pd.DataFrame({'ds': history['time_stamp'], 'y': history['cpu_scaled']})\n"
            "    pm = Prophet(daily_seasonality=True, weekly_seasonality=False)\n"
            "    pm.fit(prophet_train)\n"
            "    fc = pm.predict(pd.DataFrame({'ds': future['time_stamp']}))\n"
            "    train_fc = pm.predict(prophet_train[['ds']])\n"
            "    history['prophet_pred'] = train_fc['yhat'].values\n"
            "    history['residual_scaled'] = (history['cpu_scaled'] - history['prophet_pred'] - res_mean) / res_std\n"
            "    X = history['residual_scaled'].values[-config.input_window:].reshape(1, config.input_window, 1)\n"
            "    day1_res = (model.predict(X, verbose=0)[0] * res_std) + res_mean\n"
            "    hybrid_scaled = fc['yhat'].values + day1_res\n"
            "    actual = scaler.inverse_transform(future[['cpu_scaled']]).ravel()\n"
            "    hybrid = scaler.inverse_transform(hybrid_scaled.reshape(-1, 1)).ravel()\n"
            "    prophet_only = scaler.inverse_transform(fc['yhat'].values.reshape(-1, 1)).ravel()\n"
            "    return future['time_stamp'], actual, hybrid, prophet_only\n\n\n"
            "def monitor_unseen_container(container_id: str) -> dict:\n"
            "    \"\"\"Container-level monitoring only — no global retraining.\"\"\"\n"
            "    series = build_container_series(train_df, val_df, container_id)\n"
            "    origins = generate_origin_indices(len(series), CFG)\n"
            "    rows = [forecast_at_origin(series, origin, incumbent, res_mean, res_std, CFG).__dict__ for origin in origins]\n"
            "    monitor_df = append_rolling_metrics(pd.DataFrame(rows), CFG.rolling_window_origins)\n"
            "    monitor_df['container_id'] = container_id\n"
            "    deploy_baseline_mae = float(monitor_df.iloc[0]['hybrid_mae'])\n"
            "    deploy_baseline_prophet = float(monitor_df.iloc[0]['prophet_mae'])\n"
            "    threshold = drift_threshold(deploy_baseline_mae, CFG.relative_threshold, CFG.absolute_threshold)\n"
            "    drift_rows, diag_rows = [], []\n"
            "    for _, r in monitor_df.iterrows():\n"
            "        drift_rows.append(detect_container_drift(\n"
            "            container_id, int(r.origin_index), r.rolling_hybrid_mae, deploy_baseline_mae, CFG\n"
            "        ).__dict__)\n"
            "        diag_rows.append(classify_container(\n"
            "            container_id, int(r.origin_index), r.rolling_hybrid_mae, r.rolling_prophet_mae,\n"
            "            deploy_baseline_mae, deploy_baseline_prophet, CFG,\n"
            "        ))\n"
            "    drift_df = pd.DataFrame(drift_rows)\n"
            "    breaches = drift_df['threshold_breach']\n"
            "    first_breach = int(drift_df.loc[breaches].iloc[0]['origin_index']) if breaches.any() else None\n"
            "    trigger_diag = next((d.diagnostic_class.value for d in diag_rows if d.origin_index == first_breach), None)\n"
            "    return {\n"
            "        'container_id': container_id,\n"
            "        'series': series,\n"
            "        'origins': origins,\n"
            "        'monitor_df': monitor_df,\n"
            "        'drift_df': drift_df,\n"
            "        'diag_rows': diag_rows,\n"
            "        'deploy_baseline_mae': deploy_baseline_mae,\n"
            "        'threshold': threshold,\n"
            "        'n_breaches': int(breaches.sum()),\n"
            "        'first_breach_origin': first_breach,\n"
            "        'trigger_diagnostic': trigger_diag,\n"
            "        'max_rolling_mae': float(monitor_df['rolling_hybrid_mae'].max()),\n"
            "        'headroom': float(threshold - monitor_df['rolling_hybrid_mae'].max()),\n"
            "        'n_stable_diag': sum(1 for d in diag_rows if d.diagnostic_class == DiagnosticClass.STABLE),\n"
            "        'n_origins': len(origins),\n"
            "    }\n\n\n"
            "def container_monitoring_summary(result: dict) -> dict:\n"
            "    drift = result['n_breaches'] > 0\n"
            "    if drift:\n"
            "        action = 'added_to_drift_registry'\n"
            "        deploy_rec = 'keep_current_model (container-level; await cohort trigger)'\n"
            "        explain = (\n"
            "            'Degradation detected for this container. Registered in drift evidence. '\n"
            "            'Does NOT retrain the global Hybrid model alone.'\n"
            "        )\n"
            "    else:\n"
            "        action = 'no_action'\n"
            "        deploy_rec = DeploymentRecommendation.KEEP_CURRENT_MODEL.value\n"
            "        explain = 'Monitoring within thresholds; no drift; keep hybrid_v1 for this container.'\n"
            "    return {\n"
            "        'container_id': result['container_id'],\n"
            "        'max_rolling_mae': round(result['max_rolling_mae'], 3),\n"
            "        'threshold': round(result['threshold'], 3),\n"
            "        'drift_detected': drift,\n"
            "        'dominant_diagnostic': result['trigger_diagnostic'] or 'STABLE',\n"
            "        'container_action': action,\n"
            "        'global_retrain_triggered': False,\n"
            "        'deployment_recommendation': deploy_rec,\n"
            "        'explanation': explain,\n"
            "    }"
        ),
        md(
            "## 2. Individual Container Monitoring\n\n"
            "This section demonstrates **operational monitoring** for newly deployed unseen containers. "
            "Each container is monitored independently against its own deployment baseline.\n\n"
            "**Important:** outcomes here are **container-level only**. They feed the drift registry "
            "but do **not** directly trigger global model retraining."
        ),
        code(
            "if RESCAN_CONTAINERS or not SCAN_CSV.exists():\n"
            "    print('Scanning unseen containers...')\n"
            "    scan_rows = []\n"
            "    for i, cid in enumerate(available, 1):\n"
            "        print(f'  [{i}/{len(available)}] {cid}')\n"
            "        s = monitor_unseen_container(cid)\n"
            "        scan_rows.append({k: s[k] for k in s if k not in {'series', 'origins', 'monitor_df', 'drift_df', 'diag_rows'}})\n"
            "    scan_df = pd.DataFrame(scan_rows)\n"
            "    scan_df.to_csv(SCAN_CSV, index=False)\n"
            "else:\n"
            "    scan_df = pd.read_csv(SCAN_CSV)\n"
            "    print('Loaded cached scan:', SCAN_CSV.name)\n\n"
            "stable_pool = scan_df[(scan_df['n_breaches'] == 0) & (scan_df['n_stable_diag'] == scan_df['n_origins'])]\n"
            "stable_pool = stable_pool.sort_values(['headroom', 'deploy_baseline_mae'], ascending=[False, True])\n"
            "STABLE_ID = stable_pool.iloc[0]['container_id']\n\n"
            "drift_pool = scan_df[scan_df['n_breaches'] > 0].copy()\n"
            "drift_pool['score'] = (\n"
            "    drift_pool['n_breaches'] * 2 + drift_pool['max_consecutive_breaches'].fillna(0)\n"
            "    + drift_pool['n_recommend_diag'].fillna(0)\n"
            "    + drift_pool['trigger_diagnostic'].map({'REGIME_CHANGE': 3, 'GRU_STALE': 2, 'INVESTIGATE': 1}).fillna(0)\n"
            ")\n"
            "DRIFTED_ID = drift_pool.sort_values('score', ascending=False).iloc[0]['container_id']\n\n"
            "print('Scenario A (stable):', STABLE_ID)\n"
            "print('Scenario B (drifting):', DRIFTED_ID)"
        ),
        md(
            "### Scenario A — Stable unseen container\n\n"
            "Forecast → monitoring → rolling MAE/RMSE → **no drift** → diagnostics = STABLE → keep current model."
        ),
        code(
            "A = monitor_unseen_container(STABLE_ID)\n"
            "summary_a = container_monitoring_summary(A)\n"
            "print('Container:', STABLE_ID)\n"
            "print('Breaches:', A['n_breaches'], '| Max rolling MAE:', round(A['max_rolling_mae'], 3))"
        ),
        code(
            "fig, ax = afmlf_plots.plot_cpu_history(A['series'], title=f'Scenario A — CPU history ({STABLE_ID})')\n"
            "plt.show()\n\n"
            "first_origin = A['origins'][0]\n"
            "ts, actual, hybrid, prophet = forecast_detail(A['series'], first_origin, incumbent, res_mean, res_std, CFG)\n"
            "fig, ax = afmlf_plots.plot_forecast_origin(ts, actual, hybrid, prophet, title=f'Origin {first_origin}: Day-1 forecast vs actual')\n"
            "plt.show()\n\n"
            "fig, ax = afmlf_plots.plot_rolling_mae(A['monitor_df'], STABLE_ID)\n"
            "ax.set_title(f'Scenario A — Rolling Day-1 MAE ({STABLE_ID})')\n"
            "plt.show()\n"
            "fig, ax = afmlf_plots.plot_rolling_rmse(A['monitor_df'], STABLE_ID)\n"
            "ax.set_title(f'Scenario A — Rolling Day-1 RMSE ({STABLE_ID})')\n"
            "plt.show()\n\n"
            "display(A['drift_df'][['origin_index','rolling_hybrid_mae','threshold_value','threshold_breach']])\n"
            "fig, ax = afmlf_plots.plot_drift_threshold(A['monitor_df'], STABLE_ID, A['deploy_baseline_mae'], A['threshold'])\n"
            "plt.show()\n\n"
            "diag_a = pd.DataFrame([{'origin_index': d.origin_index, 'class': d.diagnostic_class.value, 'interpretation': d.interpretation} for d in A['diag_rows']])\n"
            "display(diag_a)\n"
            "print('CONTAINER ACTION: no_action')\n"
            "print('DEPLOYMENT (container-level): keep_current_model')\n"
            "print(summary_a['explanation'])"
        ),
        md(
            "### Scenario B — Drifting unseen container\n\n"
            "Forecast → monitoring → rolling MAE/RMSE → **threshold breach** → diagnostics "
            "(REGIME_CHANGE / GRU_STALE) → **container added to drift registry**.\n\n"
            "**Stop here.** Individual container degradation alone does **not** retrain the global Hybrid model."
        ),
        code(
            "B = monitor_unseen_container(DRIFTED_ID)\n"
            "summary_b = container_monitoring_summary(B)\n"
            "TRIGGER_B = B['first_breach_origin']\n"
            "print('Container:', DRIFTED_ID)\n"
            "print('First breach origin:', TRIGGER_B)\n"
            "print('Trigger diagnostic:', B['trigger_diagnostic'])"
        ),
        code(
            "fig, ax = afmlf_plots.plot_cpu_history(B['series'], title=f'Scenario B — CPU history ({DRIFTED_ID})')\n"
            "plt.show()\n\n"
            "first_origin = B['origins'][0]\n"
            "ts0, actual0, hybrid0, prophet0 = forecast_detail(B['series'], first_origin, incumbent, res_mean, res_std, CFG)\n"
            "fig, ax = afmlf_plots.plot_forecast_origin(ts0, actual0, hybrid0, prophet0, title=f'Origin {first_origin}: Day-1 forecast at deployment')\n"
            "plt.show()\n\n"
            "ts_t, actual_t, hybrid_t, prophet_t = forecast_detail(B['series'], TRIGGER_B, incumbent, res_mean, res_std, CFG)\n"
            "fig, ax = afmlf_plots.plot_forecast_origin(ts_t, actual_t, hybrid_t, prophet_t, title=f'Origin {TRIGGER_B}: Day-1 forecast at drift trigger')\n"
            "plt.show()\n\n"
            "fig, ax = afmlf_plots.plot_rolling_mae(B['monitor_df'], DRIFTED_ID)\n"
            "ax.set_title(f'Scenario B — Rolling Day-1 MAE ({DRIFTED_ID})')\n"
            "plt.show()\n"
            "fig, ax = afmlf_plots.plot_rolling_rmse(B['monitor_df'], DRIFTED_ID)\n"
            "ax.set_title(f'Scenario B — Rolling Day-1 RMSE ({DRIFTED_ID})')\n"
            "plt.show()\n\n"
            "display(B['drift_df'][['origin_index','rolling_hybrid_mae','threshold_value','threshold_breach']])\n"
            "fig, ax = afmlf_plots.plot_drift_threshold(B['monitor_df'], DRIFTED_ID, B['deploy_baseline_mae'], B['threshold'])\n"
            "plt.show()"
        ),
        code(
            "diag_b = pd.DataFrame([{\n"
            "    'origin_index': d.origin_index,\n"
            "    'class': d.diagnostic_class.value,\n"
            "    'interpretation': d.interpretation,\n"
            "    'recommended_action': d.recommended_action,\n"
            "} for d in B['diag_rows']])\n"
            "display(diag_b)\n"
            "trigger_row = diag_b.loc[diag_b['origin_index'] == TRIGGER_B].iloc[0]\n"
            "print('At trigger:', trigger_row['class'], '—', trigger_row['interpretation'])\n\n"
            "drift_registry_entry = pd.DataFrame([{\n"
            "    'container_id': DRIFTED_ID,\n"
            "    'first_breach_origin': TRIGGER_B,\n"
            "    'diagnostic_class': trigger_row['class'],\n"
            "    'registry_status': 'awaiting_cohort_evaluation',\n"
            "    'global_retrain_triggered': False,\n"
            "}])\n"
            "display(drift_registry_entry)\n\n"
            "print('\\n' + '='*72)\n"
            "print('CONTAINER-LEVEL OUTCOME (Scenario B)')\n"
            "print('='*72)\n"
            "print(\n"
            "    f\"The framework has identified degradation for container {DRIFTED_ID} \"\n"
            "    f\"({trigger_row['class']} at origin {TRIGGER_B}).\\n\\n\"\n"
            "    'This alone is NOT sufficient to retrain the global Hybrid model.\\n'\n"
            "    'The container is now part of the monitored population awaiting cohort-level lifecycle evaluation.'\n"
            ")"
        ),
        md(
            "### Container-level comparison\n\n"
            "Both scenarios use the same global `hybrid_v1` model. Neither unseen container alone triggers retraining."
        ),
        code(
            "container_comparison = pd.DataFrame([summary_a, summary_b])\n"
            "container_comparison.insert(0, 'scenario', ['A — Stable', 'B — Drifting'])\n"
            "display(container_comparison.T)"
        ),
        md(
            "## 3. How AFMLF Decides to Retrain the Global Model\n\n"
            "Offline candidate retraining is a **cohort-level** decision. "
            "This section uses the **official 99-container AFMLF evaluation** — frozen results, not re-run.\n\n"
            "Pipeline:\n\n"
            "```\n"
            "99 monitored containers\n"
            "  → container-level monitoring\n"
            "  → aggregate drift evidence\n"
            "  → global trigger policy\n"
            "  → offline candidate retraining\n"
            "  → candidate evaluation\n"
            "  → deployment recommendation\n"
            "```"
        ),
        code(
            "life = pd.read_csv(OFFICIAL_EXP / 'lifecycle/transitions.csv')\n"
            "decisions = pd.read_csv(OFFICIAL_EXP / 'decisions/decisions.csv')\n"
            "diag_official = pd.read_csv(OFFICIAL_EXP / 'diagnostics/diagnostics.csv')\n"
            "rec = pd.read_csv(OFFICIAL_EXP / 'recommendations/recommendations.csv')\n"
            "with (OFFICIAL_EXP / 'reports/final_report.json').open() as fh:\n"
            "    fw = json.load(fh)['framework_evaluation']\n\n"
            "n_containers = diag_official['container_id'].nunique()\n"
            "n_suspected = int((life['to_state'] == 'drift_suspected').sum())\n"
            "n_retrain_decisions = int((decisions['decision'] == 'recommend_retraining').sum())\n"
            "n_candidates = int((life['to_state'] == 'candidate_retraining').sum())\n\n"
            "cohort_funnel = pd.DataFrame([\n"
            "    {'stage': 'Containers monitored', 'count': n_containers},\n"
            "    {'stage': 'Drift suspected transitions', 'count': n_suspected},\n"
            "    {'stage': 'Global trigger satisfied (retrain recommended)', 'count': n_retrain_decisions},\n"
            "    {'stage': 'Offline candidates trained', 'count': n_candidates},\n"
            "    {'stage': 'Deployment recommendations issued', 'count': len(rec)},\n"
            "])\n"
            "display(cohort_funnel)\n\n"
            "print('Official outcome at origin 200:')\n"
            "print('  Trigger reason:', decisions.iloc[0]['trigger_reason'])\n"
            "print('  Decision:', decisions.iloc[0]['decision'])\n"
            "print('  Containers recommending retrain (diagnostics):', int(decisions.iloc[0]['n_recommend']))\n"
            "if len(rec):\n"
            "    print(f\"  Candidate ΔMAE: {rec.iloc[0]['delta_mae']:+.4f}%\")\n"
            "    print('  Deployment recommendation:', rec.iloc[0]['deployment_recommendation'])"
        ),
        code(
            "fig, ax = afmlf_plots.plot_decision_timeline(decisions)\n"
            "ax.set_title('Official cohort — decision engine at each origin')\n"
            "plt.show()\n\n"
            "fig, ax = afmlf_plots.plot_state_timeline(life)\n"
            "ax.set_title('Official cohort — lifecycle state transitions')\n"
            "plt.show()\n\n"
            "if len(rec):\n"
            "    fig, ax = afmlf_plots.plot_recommendation_quality(rec)\n"
            "    ax.set_title('Official cohort — incumbent vs candidate MAE')\n"
            "    plt.show()\n\n"
            "diag_counts = diag_official['diagnostic_class'].value_counts()\n"
            "fig, ax = afmlf_plots.plot_diagnostic_distribution(diag_official)\n"
            "ax.set_title(f'Official cohort — diagnostics ({n_containers} containers × 5 origins)')\n"
            "plt.show()\n"
            "display(diag_counts)"
        ),
        code(
            "def plot_afmlf_architecture_funnel(funnel_df):\n"
            "    \"\"\"Live matplotlib flow diagram — no external image.\"\"\"\n"
            "    labels = list(funnel_df['stage']) + ['Deployment\\nRecommendation']\n"
            "    counts = list(funnel_df['count']) + [int(funnel_df.iloc[-1]['count'])]\n"
            "    colors = ['#dbeafe', '#bfdbfe', '#93c5fd', '#60a5fa', '#2563eb', '#1d4ed8']\n"
            "    fig, ax = plt.subplots(figsize=(7, 9))\n"
            "    ax.set_xlim(0, 10)\n"
            "    ax.set_ylim(0, len(labels) * 1.35 + 1)\n"
            "    ax.axis('off')\n"
            "    y = len(labels) * 1.35\n"
            "    box_h, box_w = 0.9, 6.5\n"
            "    x = 1.75\n"
            "    for i, (label, count, color) in enumerate(zip(labels, counts, colors)):\n"
            "        rect = mpatches.FancyBboxPatch((x, y), box_w, box_h, boxstyle='round,pad=0.02', fc=color, ec='#1e3a5f', lw=1.2)\n"
            "        ax.add_patch(rect)\n"
            "        text = label if i == 0 else f\"{label}\\n(n={count})\"\n"
            "        ax.text(x + box_w/2, y + box_h/2, text, ha='center', va='center', fontsize=9, fontweight='bold' if i==0 else 'normal')\n"
            "        if i < len(labels) - 1:\n"
            "            ax.annotate('', xy=(x + box_w/2, y), xytext=(x + box_w/2, y + 0.35), arrowprops=dict(arrowstyle='->', lw=1.5, color='#334155'))\n"
            "        y -= 1.35\n"
            "    ax.text(5, len(labels)*1.35 + 0.6, 'AFMLF Global Lifecycle (Official 99-Container Run)', ha='center', fontsize=12, fontweight='bold')\n"
            "    fig.tight_layout()\n"
            "    return fig, ax\n\n"
            "fig, ax = plot_afmlf_architecture_funnel(cohort_funnel)\n"
            "plt.show()\n\n"
            "print(\n"
            "    '\\nRetraining decisions are based on the monitored population, not on an individual container.\\n'\n"
            "    f'In the official run: {n_containers} containers → {n_suspected} drift-suspected events → '\n"
            "    f'{n_retrain_decisions} global retrain recommendation → {n_candidates} candidate trained → '\n"
            "    f\"'{rec.iloc[0]['deployment_recommendation']}' deployment recommendation.\"\n"
            ")"
        ),
        md(
            "## 4. Container-Level Monitoring vs Global Model Lifecycle\n\n"
            "### Individual container (Section 2)\n\n"
            "| Responsibility | Description |\n"
            "|----------------|-------------|\n"
            "| Forecasting | Walk-forward Day-1 Hybrid forecasts using history before each origin |\n"
            "| Monitoring | Rolling MAE/RMSE per container |\n"
            "| Drift detection | Per-container threshold breach against deployment baseline |\n"
            "| Diagnostics | Prophet vs Hybrid classification (STABLE, GRU_STALE, REGIME_CHANGE, …) |\n"
            "| Outcome | Container added to drift registry **or** no action |\n\n"
            "A drifting unseen container **registers evidence** but does **not** retrain `hybrid_v1`.\n\n"
            "### Global framework (Section 3)\n\n"
            "| Responsibility | Description |\n"
            "|----------------|-------------|\n"
            "| Aggregate monitoring | Combine container-level drift evidence across the cohort |\n"
            "| Global trigger policy | Cohort fraction / median degradation thresholds |\n"
            "| Offline candidate retraining | Retrain global Hybrid on full train + accumulated val |\n"
            "| Candidate evaluation | Compare candidate vs incumbent on future origins |\n"
            "| Deployment recommendation | Deploy candidate or keep current model (human gate) |\n\n"
            "These are **different responsibilities**. Container monitoring feeds the registry; "
            "the cohort trigger decides whether the **global** model is retrained."
        ),
        code(
            "def plot_two_level_architecture():\n"
            "    \"\"\"Two-level AFMLF architecture diagram (matplotlib).\"\"\"\n"
            "    fig, ax = plt.subplots(figsize=(8, 10))\n"
            "    ax.set_xlim(0, 10)\n"
            "    ax.set_ylim(0, 12)\n"
            "    ax.axis('off')\n"
            "    steps = [\n"
            "        ('Individual Containers', '#e0e7ff', 10.5),\n"
            "        ('Monitoring', '#c7d2fe', 9.2),\n"
            "        ('Drift Registry', '#a5b4fc', 7.9),\n"
            "        ('Cohort-Level Trigger', '#818cf8', 6.2),\n"
            "        ('Offline Candidate Retraining', '#6366f1', 4.9),\n"
            "        ('Candidate Evaluation', '#4f46e5', 3.6),\n"
            "        ('Deployment Recommendation', '#4338ca', 2.3),\n"
            "    ]\n"
            "    box_w, box_h = 5.5, 0.85\n"
            "    x = 2.25\n"
            "    for i, (label, color, y) in enumerate(steps):\n"
            "        rect = mpatches.FancyBboxPatch((x, y), box_w, box_h, boxstyle='round,pad=0.02', fc=color, ec='#312e81', lw=1.2)\n"
            "        ax.add_patch(rect)\n"
            "        ax.text(x + box_w/2, y + box_h/2, label, ha='center', va='center', fontsize=10, color='white' if i >= 3 else '#1e1b4b', fontweight='bold')\n"
            "        if i < len(steps) - 1:\n"
            "            y_next = steps[i+1][2] + box_h\n"
            "            ax.annotate('', xy=(x + box_w/2, y), xytext=(x + box_w/2, y_next), arrowprops=dict(arrowstyle='->', lw=2, color='#475569'))\n"
            "    ax.axhline(7.05, xmin=0.05, xmax=0.95, color='#94a3b8', linestyle='--', lw=1)\n"
            "    ax.text(0.3, 8.8, 'Container-level\\n(Section 2)', fontsize=9, color='#64748b', va='center')\n"
            "    ax.text(0.3, 4.5, 'Global lifecycle\\n(Section 3)', fontsize=9, color='#64748b', va='center')\n"
            "    ax.set_title('AFMLF Two-Level Architecture', fontsize=13, fontweight='bold', pad=12)\n"
            "    fig.tight_layout()\n"
            "    return fig, ax\n\n"
            "fig, ax = plot_two_level_architecture()\n"
            "plt.show()"
        ),
        md(
            "## 5. Key Takeaways\n\n"
            "- **Section 2** shows container-level monitoring on two real unseen containers — stable vs drifting.\n"
            "- A **single drifting container** registers in the drift registry but **does not** retrain the global Hybrid model.\n"
            "- **Section 3** shows cohort-level lifecycle from the official 99-container evaluation: "
            "65 drift-suspected events → 1 global retrain → **keep_current_model**.\n"
            "- Container monitoring and global lifecycle are **separate responsibilities** in AFMLF design.\n"
            "- AFMLF methodology and official experiment results were **not modified**.\n"
            "- Every figure was generated **live from data** — no external images."
        ),
    ]
